apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innloggingsstatus
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  vault:
    enabled: true
    paths:
      - kvPath: /kv/{{cluster}}/sbs/innloggingsstatus/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /serviceuser/data/{{environment}}/srvinnloggstatus
        mountPath: /secret/serviceuser
      - kvPath: /apikey/apigw/{{vault_namespace}}/pdl-api/{{vault_consumer_name}}
        mountPath: /secret/pdl_apiKey
      - kvPath: /apikey/apigw/{{vault_namespace}}/security-token-service-token/{{vault_consumer_name}}
        mountPath: /secret/sts_apiKey
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi

