apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innloggingsstatus
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/innloggingsstatus/internal/isAlive
    initialDelay: 5
  readiness:
    path: /person/innloggingsstatus/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /person/innloggingsstatus/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  accessPolicy:
    rules:
      - application: pdl-api
        namespace: pdl
        cluster: dev-fss
    outbound:
      external:
        - host: {{ pdl-api-host }}
  envFrom:
    - configmap: loginservice-idporten
    - secret: innloggingsstatus-secret
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi
  azure:
    application:
      enabled: true
