apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nav-dekoratoren-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/nav-dekoratoren-api/internal/isAlive
    initialDelay: 5
  readiness:
    path: /person/nav-dekoratoren-api/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /person/nav-dekoratoren-api/internal/metrics
  replicas:
    min: 2
    max: 8
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  accessPolicy:
    outbound:
      rules:
        - namespace: min-side
          application: tms-varselbjelle-api
      external:
        - host: {{ pdl-api-host }}
  envFrom:
    - configmap: loginservice-idporten
    - secret: nav-dekoratoren-api-secret
  resources:
    limits:
      cpu: "3"
      memory: 1536Mi
    requests:
      cpu: "50m"
      memory: 384Mi
  azure:
    application:
      enabled: true
